<?php

/**
 * @file
 * Contains h5p_extras.module.
 */
 
 /**
 * Alter a library's semantics
 *
 * May be used to add more fields to a library, change a widget, add more allowed tags for
 * a textfield etc
 *
 * @param array $semantics
 * A libraries definition of the data the library uses
 * @param string $machine_name
 * The libraries machine name
 * @param int $major_version
 * Major version for the library
 * @param int $minor_version
 * Minor version fot the library
 */


use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function h5p_extras_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the h5p_extras module.
    case 'help.page.h5p_extras':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Create extra functionality to H5P in Drupal 8') . '</p>';
      return $output;

    default:
  }
}



/**
 * Add styles to H5Ps
 *
 * @param array $styles
 *  Array of objects with properties path and version. Version is on the form
 *  ?ver=1.0.2 and is used as a cache buster
 * @param array $libraries
 *  Array of libraries indexed by the library's machineName and with an array
 *  as value. The value has the properties majorVersion and minorVersion
 * @param string $mode
 *  What mode are we in? Possible values are "editor", "div", "iframe" and "external"
 */

function h5p_extras_h5p_styles_alter(&$styles, &$libraries, $mode) {
  // Add special styles for all H5P Content
  $styles[] = (object) array(
    'path' => drupal_get_path('module', 'h5p_extras') . '/css/h5p-global-overrides.css',
    'version' => '?ver=1',
  );


  $libraries[] = 'h5p_extras/global';
}


/**
 * Add scrpits to H5Ps
 */

function h5p_css_overrides_h5p_scripts_alter(&$scripts, & $libraries, $mode) {
   // Add special styles for all H5P Content
   $scripts[] = (object) array(
     'path' => drupal_get_path('module', 'h5p_extras') . '/js/h5p-global-overrides.js',
     'version' => '?ver=1',
   );


   $libraries[] = 'h5p_extras/global';
 }
